/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tsb;

import com.tsb.model.GameScore;
import com.tsb.model.PlayerNumber;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class GameScoreTest {
    @Test
    @DisplayName("Выигрыш 4-х очков с перевесом, по крайней мере, в 2 очка")
    void winGameWithoutBalance() {
        GameScore score = new GameScore();
        for (int i = 0; i < GameScore.DEFAULT_POINTS_TO_WIN - 1; i++) {
            score.aceWon(PlayerNumber.PLAYER_1);
            Assertions.assertFalse(score.isWinning());
        }
        score.aceWon(PlayerNumber.PLAYER_1);
        Assertions.assertTrue(score.isWinning());
    }

    @Test
    @DisplayName("Если достигнут счет 3-3, выигрыш достигается при перевесе, в 2 очка")
    void winGameWithBalance() {
        GameScore score = new GameScore();
        for (int i = 0; i < GameScore.DEFAULT_POINTS_TO_WIN; i++) {
            score.aceWon(PlayerNumber.PLAYER_1);
            score.aceWon(PlayerNumber.PLAYER_2);
            Assertions.assertFalse(score.isWinning());
        }
        score.aceWon(PlayerNumber.PLAYER_2);
        Assertions.assertFalse(score.isWinning());
        score.aceWon(PlayerNumber.PLAYER_2);
        Assertions.assertTrue(score.isWinning());
    }
}
