/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tsb;

import com.tsb.model.GameScore;
import com.tsb.model.PlayerNumber;
import com.tsb.model.SetScore;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class SetScoreTest {

    @Test
    @DisplayName("Выигрыш 6-ти геймов с перевесом, по крайней мере, в 2 гейма")
    void winSetWithoutBalance() {
        SetScore score = new SetScore();
        for (int i = 0; i < SetScore.DEFAULT_GAMES_TO_WIN - 1; i++) {
            for (int j = 0; j < GameScore.DEFAULT_POINTS_TO_WIN; j++) {
                score.aceWon(PlayerNumber.PLAYER_1);
            }
        }
        for (int j = 0; j < GameScore.DEFAULT_POINTS_TO_WIN - 1; j++) {
            score.aceWon(PlayerNumber.PLAYER_1);
            Assertions.assertFalse(score.isWinning());
        }
        score.aceWon(PlayerNumber.PLAYER_1);
        Assertions.assertTrue(score.isWinning());
    }

    @Test
    @DisplayName("Если счёт становится 6-6, то разыгрывается тай-брейк.")
    void winSetWithBalance() {
        SetScore score = new SetScore();
        for (int i = 0; i < SetScore.DEFAULT_GAMES_TO_WIN; i++) {
            for (int j = 0; j < GameScore.DEFAULT_POINTS_TO_WIN; j++) {
                score.aceWon(PlayerNumber.PLAYER_1);
            }
            for (int j = 0; j < GameScore.DEFAULT_POINTS_TO_WIN; j++) {
                score.aceWon(PlayerNumber.PLAYER_2);
            }
        }
        for (int j = 0; j < SetScore.POINTS_TO_WIN_TIME_BREAK_GAME - 1; j++) {
            score.aceWon(PlayerNumber.PLAYER_1);
            Assertions.assertFalse(score.isWinning());
        }

        score.aceWon(PlayerNumber.PLAYER_1);
        Assertions.assertTrue(score.isWinning());
    }
}
