services:
  postgres:
    image: postgres:15.5
    container_name: tsb_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - tsb_dbdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
volumes:
  tsb_dbdata:

